### ISSUE TITLE
SSR的一些问题

### ISSUE THREAD

**Issue by paddingme** [paddingme/paddingme.github.io#16]
- 为什么需要 SSR
	
	- 首先是 SEO， 服务器端直接渲染出页面，搜索引擎可以直接抓取，与客户端异步加载页面，搜索引擎是不会等待异步加载完成的；
	- 首先当然是服务区端渲染直出要比客户端快，这样就会有更少的内容到达时间，不用让用户等着菊花一直转儿转的。
	
这里就涉及到正确使用 SSR 的场景了，所以有用户登录的页面需要 SSR 吗？

首先这样的页面不需要 SEO， 你不会告诉搜索引擎怎么登录吧，搜索引擎又没有账号, 再者我狭义的理解SEO就是一个 URL 对应 一个网页内容，这个网页内容不是动态的。

更尴尬的是发现一个问题， SSR 之后所有静态资源和 我的 graphql 请求 竟然是两个截然不同的 cookie, 这导致我再后端的 graphql 不能正确读取到用户， 这很尴尬。 可能是 客户端的 vue apollo 没有正确打包到 webpack server 端，哎， 先看看怎么解决，如果不能解决，只好把用户标识传入到 graphql 参数中以获取当前用户了。

**Comment by paddingme** [comment]
test

**Comment by paddingme** [comment]
打撒打撒

**Comment by paddingme** [comment]
2333

**Comment by yahoo2651** [comment]
2222
