### ISSUE TITLE
你好，您的博客padding.me这个地址打不开了

### ISSUE THREAD

**Issue by FredWe** [paddingme/paddingme.github.io#8]
![image](https://cloud.githubusercontent.com/assets/7354718/8447537/0531d29e-1fed-11e5-8a3e-baaca20d1fca.png)

**Comment by paddingme** [comment]
谢谢，国内托管在gitcafe 上，GitCafe Pages 服务由于受攻击暂时下线了，现已修复，再次感谢提醒。
